[package]
name = "nixdocs"
version = "0.1.0"
authors = ["mlvzk <mlvzk@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rnix = "0.8"
crc32fast = "1.2"
serde = { verson = "1.0", features = [ "derive" ] }
bincode = "1.3"
walkdir = "2.0"
rayon = "1.3"
colored = "2.0"
