[package]
name = "manix"
description = "Nix documentation searcher"
version = "0.2.4"
authors = ["mlvzk <mlvzk@protonmail.com>"]
edition = "2018"
license = "MPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rnix = "0.8"
crc32fast = "1.2"
serde = { version = "1.0", features = [ "derive"  ] }
serde_json = "1.0"
bincode = "1.3"
walkdir = "2.0"
rayon = "1.3"
colored = "2.0"
xdg = "2.2"
lazy_static = "1.4"
